// Generated by gencpp from file led_tutorial/SetRGBAnalogResponse.msg
// DO NOT EDIT!


#ifndef LED_TUTORIAL_MESSAGE_SETRGBANALOGRESPONSE_H
#define LED_TUTORIAL_MESSAGE_SETRGBANALOGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace led_tutorial
{
template <class ContainerAllocator>
struct SetRGBAnalogResponse_
{
  typedef SetRGBAnalogResponse_<ContainerAllocator> Type;

  SetRGBAnalogResponse_()
    : result()
    , message()
    , Timestamp()  {
    }
  SetRGBAnalogResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)
    , message(_alloc)
    , Timestamp()  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _result_type;
  _result_type result;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef ros::Time _Timestamp_type;
  _Timestamp_type Timestamp;





  typedef boost::shared_ptr< ::led_tutorial::SetRGBAnalogResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::led_tutorial::SetRGBAnalogResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetRGBAnalogResponse_

typedef ::led_tutorial::SetRGBAnalogResponse_<std::allocator<void> > SetRGBAnalogResponse;

typedef boost::shared_ptr< ::led_tutorial::SetRGBAnalogResponse > SetRGBAnalogResponsePtr;
typedef boost::shared_ptr< ::led_tutorial::SetRGBAnalogResponse const> SetRGBAnalogResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::led_tutorial::SetRGBAnalogResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::led_tutorial::SetRGBAnalogResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::led_tutorial::SetRGBAnalogResponse_<ContainerAllocator1> & lhs, const ::led_tutorial::SetRGBAnalogResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.message == rhs.message &&
    lhs.Timestamp == rhs.Timestamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::led_tutorial::SetRGBAnalogResponse_<ContainerAllocator1> & lhs, const ::led_tutorial::SetRGBAnalogResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace led_tutorial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::led_tutorial::SetRGBAnalogResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::led_tutorial::SetRGBAnalogResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::led_tutorial::SetRGBAnalogResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::led_tutorial::SetRGBAnalogResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::led_tutorial::SetRGBAnalogResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::led_tutorial::SetRGBAnalogResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::led_tutorial::SetRGBAnalogResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad1c7d9d0ff8ca871b1c881c758f3f9b";
  }

  static const char* value(const ::led_tutorial::SetRGBAnalogResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad1c7d9d0ff8ca87ULL;
  static const uint64_t static_value2 = 0x1b1c881c758f3f9bULL;
};

template<class ContainerAllocator>
struct DataType< ::led_tutorial::SetRGBAnalogResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "led_tutorial/SetRGBAnalogResponse";
  }

  static const char* value(const ::led_tutorial::SetRGBAnalogResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::led_tutorial::SetRGBAnalogResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
"string message\n"
"time   Timestamp\n"
"\n"
;
  }

  static const char* value(const ::led_tutorial::SetRGBAnalogResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::led_tutorial::SetRGBAnalogResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.message);
      stream.next(m.Timestamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRGBAnalogResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::led_tutorial::SetRGBAnalogResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::led_tutorial::SetRGBAnalogResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.result);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "Timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.Timestamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LED_TUTORIAL_MESSAGE_SETRGBANALOGRESPONSE_H
