// Generated by gencpp from file led_tutorial/SetRGBAnalog.msg
// DO NOT EDIT!


#ifndef LED_TUTORIAL_MESSAGE_SETRGBANALOG_H
#define LED_TUTORIAL_MESSAGE_SETRGBANALOG_H

#include <ros/service_traits.h>


#include <led_tutorial/SetRGBAnalogRequest.h>
#include <led_tutorial/SetRGBAnalogResponse.h>


namespace led_tutorial
{

struct SetRGBAnalog
{

typedef SetRGBAnalogRequest Request;
typedef SetRGBAnalogResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRGBAnalog
} // namespace led_tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::led_tutorial::SetRGBAnalog > {
  static const char* value()
  {
    return "e9c8c842901f7001b386259a45987503";
  }

  static const char* value(const ::led_tutorial::SetRGBAnalog&) { return value(); }
};

template<>
struct DataType< ::led_tutorial::SetRGBAnalog > {
  static const char* value()
  {
    return "led_tutorial/SetRGBAnalog";
  }

  static const char* value(const ::led_tutorial::SetRGBAnalog&) { return value(); }
};


// service_traits::MD5Sum< ::led_tutorial::SetRGBAnalogRequest> should match
// service_traits::MD5Sum< ::led_tutorial::SetRGBAnalog >
template<>
struct MD5Sum< ::led_tutorial::SetRGBAnalogRequest>
{
  static const char* value()
  {
    return MD5Sum< ::led_tutorial::SetRGBAnalog >::value();
  }
  static const char* value(const ::led_tutorial::SetRGBAnalogRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::led_tutorial::SetRGBAnalogRequest> should match
// service_traits::DataType< ::led_tutorial::SetRGBAnalog >
template<>
struct DataType< ::led_tutorial::SetRGBAnalogRequest>
{
  static const char* value()
  {
    return DataType< ::led_tutorial::SetRGBAnalog >::value();
  }
  static const char* value(const ::led_tutorial::SetRGBAnalogRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::led_tutorial::SetRGBAnalogResponse> should match
// service_traits::MD5Sum< ::led_tutorial::SetRGBAnalog >
template<>
struct MD5Sum< ::led_tutorial::SetRGBAnalogResponse>
{
  static const char* value()
  {
    return MD5Sum< ::led_tutorial::SetRGBAnalog >::value();
  }
  static const char* value(const ::led_tutorial::SetRGBAnalogResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::led_tutorial::SetRGBAnalogResponse> should match
// service_traits::DataType< ::led_tutorial::SetRGBAnalog >
template<>
struct DataType< ::led_tutorial::SetRGBAnalogResponse>
{
  static const char* value()
  {
    return DataType< ::led_tutorial::SetRGBAnalog >::value();
  }
  static const char* value(const ::led_tutorial::SetRGBAnalogResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LED_TUTORIAL_MESSAGE_SETRGBANALOG_H
