// Generated by gencpp from file led_tutorial/SetRGBDigital.msg
// DO NOT EDIT!


#ifndef LED_TUTORIAL_MESSAGE_SETRGBDIGITAL_H
#define LED_TUTORIAL_MESSAGE_SETRGBDIGITAL_H

#include <ros/service_traits.h>


#include <led_tutorial/SetRGBDigitalRequest.h>
#include <led_tutorial/SetRGBDigitalResponse.h>


namespace led_tutorial
{

struct SetRGBDigital
{

typedef SetRGBDigitalRequest Request;
typedef SetRGBDigitalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRGBDigital
} // namespace led_tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::led_tutorial::SetRGBDigital > {
  static const char* value()
  {
    return "9df6cef7d28f2f7dca06723b950a75f7";
  }

  static const char* value(const ::led_tutorial::SetRGBDigital&) { return value(); }
};

template<>
struct DataType< ::led_tutorial::SetRGBDigital > {
  static const char* value()
  {
    return "led_tutorial/SetRGBDigital";
  }

  static const char* value(const ::led_tutorial::SetRGBDigital&) { return value(); }
};


// service_traits::MD5Sum< ::led_tutorial::SetRGBDigitalRequest> should match
// service_traits::MD5Sum< ::led_tutorial::SetRGBDigital >
template<>
struct MD5Sum< ::led_tutorial::SetRGBDigitalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::led_tutorial::SetRGBDigital >::value();
  }
  static const char* value(const ::led_tutorial::SetRGBDigitalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::led_tutorial::SetRGBDigitalRequest> should match
// service_traits::DataType< ::led_tutorial::SetRGBDigital >
template<>
struct DataType< ::led_tutorial::SetRGBDigitalRequest>
{
  static const char* value()
  {
    return DataType< ::led_tutorial::SetRGBDigital >::value();
  }
  static const char* value(const ::led_tutorial::SetRGBDigitalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::led_tutorial::SetRGBDigitalResponse> should match
// service_traits::MD5Sum< ::led_tutorial::SetRGBDigital >
template<>
struct MD5Sum< ::led_tutorial::SetRGBDigitalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::led_tutorial::SetRGBDigital >::value();
  }
  static const char* value(const ::led_tutorial::SetRGBDigitalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::led_tutorial::SetRGBDigitalResponse> should match
// service_traits::DataType< ::led_tutorial::SetRGBDigital >
template<>
struct DataType< ::led_tutorial::SetRGBDigitalResponse>
{
  static const char* value()
  {
    return DataType< ::led_tutorial::SetRGBDigital >::value();
  }
  static const char* value(const ::led_tutorial::SetRGBDigitalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LED_TUTORIAL_MESSAGE_SETRGBDIGITAL_H
