# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from echo_tutorial/EchoDistance.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class EchoDistance(genpy.Message):
  _md5sum = "d7755fc5d2735bcfbf5a864c13aab9ab"
  _type = "echo_tutorial/EchoDistance"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time Stamp
float64 Distance
"""
  __slots__ = ['Stamp','Distance']
  _slot_types = ['time','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Stamp,Distance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EchoDistance, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.Stamp is None:
        self.Stamp = genpy.Time()
      if self.Distance is None:
        self.Distance = 0.
    else:
      self.Stamp = genpy.Time()
      self.Distance = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2Id().pack(_x.Stamp.secs, _x.Stamp.nsecs, _x.Distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.Stamp is None:
        self.Stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.Stamp.secs, _x.Stamp.nsecs, _x.Distance,) = _get_struct_2Id().unpack(str[start:end])
      self.Stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2Id().pack(_x.Stamp.secs, _x.Stamp.nsecs, _x.Distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.Stamp is None:
        self.Stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.Stamp.secs, _x.Stamp.nsecs, _x.Distance,) = _get_struct_2Id().unpack(str[start:end])
      self.Stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2Id = None
def _get_struct_2Id():
    global _struct_2Id
    if _struct_2Id is None:
        _struct_2Id = struct.Struct("<2Id")
    return _struct_2Id
